import type { PortfolioData } from '../types'

export const EXAMPLE_PORTFOLIO: PortfolioData = {
  version: 3,
  username: 'maya-chen',
  avatarUrl: '/example-avatar.jpg',
  name: 'Maya Chen',
  headline: 'Full-stack developer building focused products for real people.',
  bio: 'I care about reliable software, clear interfaces, and turning ambiguous product ideas into useful experiences. My work spans TypeScript, React, Node.js, and Python.',
  location: 'Vancouver, Canada',
  githubUrl: 'https://github.com',
  website: 'https://example.com',
  email: 'maya.chen@example.com',
  skills: ['TypeScript', 'React', 'Node.js', 'Python', 'PostgreSQL', 'Docker', 'REST APIs', 'Testing'],
  projects: [
    {
      id: 1,
      originalName: 'realtime-board',
      title: 'Realtime Board',
      description: 'A collaborative planning workspace with optimistic updates, presence, and a lightweight permission model for small product teams.',
      url: 'https://github.com',
      homepage: 'https://example.com',
      language: 'TypeScript',
      technologies: ['TypeScript', 'React', 'Node.js', 'WebSockets'],
      stars: 128,
      forks: 18,
      selected: true,
      featured: true,
    },
    {
      id: 2,
      originalName: 'deploy-cli',
      title: 'Deploy CLI',
      description: 'A compact deployment workflow that validates configuration, streams build output, and keeps releases reproducible.',
      url: 'https://github.com',
      homepage: '',
      language: 'Go',
      technologies: ['Go', 'Docker', 'GitHub Actions'],
      stars: 64,
      forks: 9,
      selected: true,
      featured: false,
    },
    {
      id: 3,
      originalName: 'open-notes',
      title: 'Open Notes',
      description: 'A keyboard-first markdown workspace focused on speed, local-first editing, and a distraction-free reading experience.',
      url: 'https://github.com',
      homepage: 'https://example.com',
      language: 'TypeScript',
      technologies: ['React', 'TypeScript', 'IndexedDB'],
      stars: 42,
      forks: 6,
      selected: true,
      featured: false,
    },
    {
      id: 4,
      originalName: 'api-monitor',
      title: 'API Monitor',
      description: 'Simple endpoint monitoring with scheduled checks, incident history, and concise notifications for small engineering teams.',
      url: 'https://github.com',
      homepage: '',
      language: 'Python',
      technologies: ['Python', 'FastAPI', 'PostgreSQL'],
      stars: 31,
      forks: 4,
      selected: true,
      featured: false,
    },
  ],
  hero: {
    eyebrow: 'Full-stack developer',
    status: 'Open to product engineering roles',
    showStatus: true,
    availabilityConfirmed: true,
    showImage: true,
  },
  appearance: {
    template: 'creative',
    mode: 'dark',
    accent: '#4a9eff',
    font: 'sans',
  },
  sections: {
    about: {
      visible: true,
      title: 'About',
      text: 'I like building software where engineering quality and product clarity reinforce each other. I enjoy taking features from rough requirements through implementation, testing, and the final user-facing details.',
    },
    experience: {
      visible: true,
      title: 'Experience',
      items: [
        {
          id: 'example-exp-1',
          title: 'Product Engineer',
          subtitle: 'Northstar Studio',
          meta: '2025 — Now',
          description: 'Building internal and customer-facing workflows across React, Node.js, and PostgreSQL while collaborating closely with product and design.',
        },
        {
          id: 'example-exp-2',
          title: 'Software Engineering Intern',
          subtitle: 'Field Labs',
          meta: '2024',
          description: 'Shipped backend API improvements, strengthened test coverage, and helped simplify a legacy admin workflow.',
        },
      ],
    },
    education: {
      visible: true,
      title: 'Education',
      items: [
        {
          id: 'example-edu-1',
          title: 'MSc Software Engineering',
          subtitle: 'Technical University',
          meta: '2023 — 2025',
          description: 'Distributed systems, software architecture, databases, and applied product development.',
        },
      ],
    },
    certifications: { visible: false, title: 'Certifications', items: [] },
    achievements: { visible: false, title: 'Achievements', items: [] },
    skills: { visible: true, title: 'Skills' },
    projects: { visible: true, title: 'Selected work' },
    contact: {
      visible: true,
      title: 'Let’s make something useful.',
      text: 'I’m interested in thoughtful product teams, freelance collaborations, and engineering work where craft matters.',
    },
  },
}
